const DEFAULT_RESTAURANT = {
    name: 'First Coffee',
    tagline: 'Restaurant',
    address: 'Haya hulet Infront of Addis hiwot hospital , Addis Ababa, Ethiopia',
    phone: '+251 911 234 567',
    hours: 'Mon-Sun: 7:00 AM - 10:00 PM',
    currency: 'ETB',
    social: 'https://www.instagram.com/firstcoffee'
};

const DEFAULT_CATEGORIES = [
    { id: 'cat-1', name: 'Espresso & Coffee', order: 1 },
    { id: 'cat-2', name: 'Hot Drinks', order: 2 },
    { id: 'cat-3', name: 'Cold Drinks', order: 3 },
    { id: 'cat-4', name: 'Pastries & Cakes', order: 4 },
    { id: 'cat-5', name: 'Traditional Foods', order: 5 },
    { id: 'cat-6', name: 'Lunch', order: 6 },
    { id: 'cat-7', name: 'Dinner', order: 7 },
    { id: 'cat-8', name: 'Desserts', order: 8 }
];

const DEFAULT_ITEMS = [
    {
        id: 'item-1',
        name: 'Ethiopian Macchiato',
        description: 'Rich espresso stained with a dash of velvety steamed milk, served in a traditional glass.',
        price: 85,
        categoryId: 'cat-1',
        image: '',
        tags: ['popular'],
        available: true,
        featured: true,
        popular: true,
        note: 'Made with Yirgacheffe beans',
        allergens: 'Milk',
        dietary: [],
        options: [],
        order: 1
    },
    {
        id: 'item-2',
        name: 'Cappuccino',
        description: 'Equal parts espresso, steamed milk, and a thick crown of microfoam. A timeless classic.',
        price: 120,
        categoryId: 'cat-1',
        image: '',
        tags: ['popular'],
        available: true,
        featured: true,
        popular: true,
        note: '',
        allergens: 'Milk',
        dietary: [],
        options: [{ name: 'Size', choices: ['Small', 'Medium', 'Large'], required: false }],
        order: 2
    },
    {
        id: 'item-3',
        name: 'Americano',
        description: 'Bold Ethiopian espresso diluted with hot water for a smooth, clean finish.',
        price: 95,
        categoryId: 'cat-1',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: '',
        dietary: ['vegan', 'gluten-free', 'dairy-free'],
        options: [],
        order: 3
    },
    {
        id: 'item-4',
        name: 'Latte',
        description: 'Silky steamed milk poured over a shot of espresso, finished with a light foam layer.',
        price: 130,
        categoryId: 'cat-1',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Milk',
        dietary: ['vegetarian'],
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Soy'], required: false }],
        order: 4
    },
    {
        id: 'item-5',
        name: 'Flat White',
        description: 'Velvety microfoam merged with a double ristretto for intense coffee flavor.',
        price: 140,
        categoryId: 'cat-1',
        image: '',
        tags: [],
        available: true,
        featured: true,
        popular: false,
        note: '',
        allergens: 'Milk',
        dietary: ['vegetarian'],
        options: [],
        order: 5
    },
    {
        id: 'item-6',
        name: 'Mocha',
        description: 'Espresso, steamed milk, and rich chocolate syrup, topped with whipped cream.',
        price: 160,
        categoryId: 'cat-1',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Milk, Dairy',
        dietary: ['vegetarian'],
        options: [{ name: 'Topping', choices: ['Whipped Cream', 'Marshmallows', 'None'], required: false }],
        order: 6
    },
    {
        id: 'item-7',
        name: 'Spiced Chai Latte',
        description: 'Aromatic black tea brewed with cinnamon, cardamom, ginger, and cloves, steamed with milk.',
        price: 145,
        categoryId: 'cat-2',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Can be made dairy-free',
        allergens: 'Milk (optional)',
        dietary: ['vegetarian', 'gluten-free'],
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Almond'], required: false }],
        order: 1
    },
    {
        id: 'item-8',
        name: 'Hot Chocolate',
        description: 'Premium Belgian chocolate melted into steamed milk, topped with marshmallows.',
        price: 135,
        categoryId: 'cat-2',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Milk, Dairy',
        dietary: ['vegetarian'],
        options: [],
        order: 2
    },
    {
        id: 'item-9',
        name: 'Turmeric Latte',
        description: 'Warming golden milk with turmeric, cinnamon, honey, and a hint of black pepper.',
        price: 150,
        categoryId: 'cat-2',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: '',
        allergens: 'Milk',
        dietary: ['vegetarian'],
        options: [{ name: 'Sweetener', choices: ['Honey', 'Maple Syrup', 'None'], required: false }],
        order: 3
    },
    {
        id: 'item-10',
        name: 'Iced Americano',
        description: 'Chilled espresso over ice for a crisp, refreshing coffee experience.',
        price: 105,
        categoryId: 'cat-3',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: '',
        dietary: ['vegan', 'gluten-free', 'dairy-free'],
        options: [{ name: 'Size', choices: ['Regular', 'Large'], required: false }],
        order: 1
    },
    {
        id: 'item-11',
        name: 'Iced Latte',
        description: 'Cool espresso and cold milk over ice, perfectly balanced and refreshing.',
        price: 140,
        categoryId: 'cat-3',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Milk',
        dietary: ['vegetarian'],
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Soy'], required: false }],
        order: 2
    },
    {
        id: 'item-12',
        name: 'Cold Brew',
        description: 'Slow-steeped for 18 hours for a smooth, low-acidity coffee concentrate.',
        price: 155,
        categoryId: 'cat-3',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Available with oat milk',
        allergens: '',
        dietary: ['vegan', 'gluten-free', 'dairy-free'],
        options: [],
        order: 3
    },
    {
        id: 'item-13',
        name: 'Butter Croissant',
        description: 'Flaky, golden, and perfectly buttery. Baked fresh every morning.',
        price: 110,
        categoryId: 'cat-4',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Best served warm',
        allergens: 'Gluten, Dairy, Eggs',
        dietary: [],
        options: [],
        order: 1
    },
    {
        id: 'item-14',
        name: 'Almond Croissant',
        description: 'Buttery croissant filled with almond cream and topped with toasted almond flakes.',
        price: 140,
        categoryId: 'cat-4',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Nuts, Eggs',
        dietary: [],
        options: [],
        order: 2
    },
    {
        id: 'item-15',
        name: 'Pain au Chocolat',
        description: 'Flaky croissant dough wrapped around rich dark chocolate batons.',
        price: 125,
        categoryId: 'cat-4',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Chocolate',
        dietary: [],
        options: [],
        order: 3
    },
    {
        id: 'item-16',
        name: 'Chocolate Layer Cake',
        description: 'Three layers of moist chocolate cake with ganache and dark chocolate shavings.',
        price: 280,
        categoryId: 'cat-4',
        image: '',
        tags: ['popular', 'featured'],
        available: true,
        featured: true,
        popular: true,
        note: 'Serves 2-3',
        allergens: 'Gluten, Dairy, Eggs',
        dietary: [],
        options: [],
        order: 4
    },
    {
        id: 'item-17',
        name: 'Caramel Cheesecake',
        description: 'Creamy New York cheesecake with a salted caramel drizzle and graham cracker crust.',
        price: 260,
        categoryId: 'cat-4',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Dairy, Gluten, Eggs',
        dietary: [],
        options: [],
        order: 5
    },
    {
        id: 'item-18',
        name: 'Tiramisu',
        description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream.',
        price: 240,
        categoryId: 'cat-4',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Contains alcohol',
        allergens: 'Dairy, Gluten, Eggs, Alcohol',
        dietary: ['vegetarian'],
        options: [],
        order: 6
    },
    {
        id: 'item-19',
        name: 'Custom Whole Cake',
        description: 'Design your own cake. Choose flavor, size, and decorations. 48-hour notice required.',
        price: 1200,
        categoryId: 'cat-4',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: '48-hour advance order',
        allergens: 'Varies by flavor',
        dietary: [],
        options: [{ name: 'Flavor', choices: ['Chocolate', 'Vanilla', 'Red Velvet', 'Carrot'], required: true }, { name: 'Size', choices: ['6 inch', '8 inch', '10 inch'], required: true }],
        order: 7
    },
    {
        id: 'item-20',
        name: 'Full Breakfast',
        description: 'Scrambled eggs, grilled tomato, sausage, beans, toast, and hash browns.',
        price: 320,
        categoryId: 'cat-5',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Served with coffee or tea',
        allergens: 'Gluten, Dairy, Eggs',
        dietary: [],
        options: [],
        order: 1
    },
    {
        id: 'item-21',
        name: 'Avocado Toast',
        description: 'Sourdough bread topped with smashed avocado, chili flakes, sea salt, and microgreens.',
        price: 210,
        categoryId: 'cat-5',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Add poached egg +45 ETB',
        allergens: 'Gluten',
        dietary: ['vegetarian', 'vegan-option'],
        options: [{ name: 'Add', choices: ['Poached Egg', 'Feta Cheese', 'None'], required: false }],
        order: 2
    },
    {
        id: 'item-22',
        name: 'Club Sandwich',
        description: 'Triple-decker sandwich with roasted chicken, bacon, lettuce, tomato, and mayo.',
        price: 280,
        categoryId: 'cat-6',
        image: '',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Served with fries',
        allergens: 'Gluten, Dairy',
        dietary: [],
        options: [],
        order: 1
    },
    {
        id: 'item-23',
        name: 'Pasta Carbonara',
        description: 'Spaghetti with creamy egg sauce, crispy pancetta, and parmesan.',
        price: 340,
        categoryId: 'cat-6',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Eggs',
        dietary: ['vegetarian'],
        options: [{ name: 'Add', choices: ['Extra Pancetta', 'Garlic Bread', 'None'], required: false }],
        order: 2
    },
    {
        id: 'item-24',
        name: 'Crème Brûlée',
        description: 'Rich vanilla custard with a caramelized sugar crust. Classic French dessert.',
        price: 190,
        categoryId: 'cat-8',
        image: '',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Dairy, Eggs',
        dietary: ['vegetarian'],
        options: [],
        order: 1
    },
    {
        id: 'item-25',
        name: 'Seasonal Fruit Plate',
        description: 'Fresh seasonal fruits beautifully arranged. Light and refreshing.',
        price: 170,
        categoryId: 'cat-8',
        image: '',
        tags: [],
        available: false,
        featured: false,
        popular: false,
        note: 'Subject to availability',
        allergens: '',
        dietary: ['vegan', 'gluten-free', 'dairy-free'],
        options: [],
        order: 2
    },
    {
        id: 'item-26',
        name: 'Chef\'s Daily Special',
        description: 'Ask your server about today\'s special creation from our kitchen.',
        price: 350,
        categoryId: 'cat-7',
        image: '',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Changes daily',
        allergens: 'Varies',
        dietary: [],
        options: [],
        order: 1
    }
];

function generateId(prefix) {
    return prefix + '-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
}
