const DEFAULT_RESTAURANT = {
    name: 'First Coffee',
    tagline: 'Restaurant',
    address: 'Bole Road, Addis Ababa, Ethiopia',
    phone: '+251 911 234 567',
    hours: 'Mon-Sun: 7:00 AM - 10:00 PM',
    currency: 'ETB',
    social: 'https://www.instagram.com/firstcoffee'
};

const DEFAULT_CATEGORIES = [
    { id: 'cat-1', name: 'Espresso & Coffee', order: 1 },
    { id: 'cat-2', name: 'Hot Drinks', order: 2 },
    { id: 'cat-3', name: 'Cold Drinks', order: 3 },
    { id: 'cat-4', name: 'Pastries', order: 4 },
    { id: 'cat-5', name: 'Cakes', order: 5 },
    { id: 'cat-6', name: 'Whole Cakes', order: 6 },
    { id: 'cat-7', name: 'Breakfast', order: 7 },
    { id: 'cat-8', name: 'Food', order: 8 },
    { id: 'cat-9', name: 'Desserts', order: 9 },
    { id: 'cat-10', name: 'Specials', order: 10 }
];

const DEFAULT_ITEMS = [
    {
        id: 'item-1',
        name: 'Ethiopian Macchiato',
        description: 'Rich espresso stained with a dash of velvety steamed milk, served in a traditional glass.',
        price: 85,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: true,
        popular: true,
        note: 'Made with Yirgacheffe beans',
        allergens: 'Milk',
        options: [],
        order: 1
    },
    {
        id: 'item-2',
        name: 'Cappuccino',
        description: 'Equal parts espresso, steamed milk, and a thick crown of microfoam. A timeless classic.',
        price: 120,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: true,
        popular: true,
        note: '',
        allergens: 'Milk',
        options: [{ name: 'Size', choices: ['Small', 'Medium', 'Large'], required: false }],
        order: 2
    },
    {
        id: 'item-3',
        name: 'Americano',
        description: 'Bold Ethiopian espresso diluted with hot water for a smooth, clean finish.',
        price: 95,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1551030173-122aabc4489c?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: '',
        options: [],
        order: 3
    },
    {
        id: 'item-4',
        name: 'Latte',
        description: 'Silky steamed milk poured over a shot of espresso, finished with a light foam layer.',
        price: 130,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1461023058943-35fc6a22b067?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Milk',
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Soy'], required: false }],
        order: 4
    },
    {
        id: 'item-5',
        name: 'Flat White',
        description: 'Velvety microfoam merged with a double ristretto for intense coffee flavor.',
        price: 140,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1541167760496-1628856ab1f0?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: true,
        popular: false,
        note: '',
        allergens: 'Milk',
        options: [],
        order: 5
    },
    {
        id: 'item-6',
        name: 'Mocha',
        description: 'Espresso, steamed milk, and rich chocolate syrup, topped with whipped cream.',
        price: 160,
        categoryId: 'cat-1',
        image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Milk, Dairy',
        options: [{ name: 'Topping', choices: ['Whipped Cream', 'Marshmallows', 'None'], required: false }],
        order: 6
    },
    {
        id: 'item-7',
        name: 'Spiced Chai Latte',
        description: 'Aromatic black tea brewed with cinnamon, cardamom, ginger, and cloves, steamed with milk.',
        price: 145,
        categoryId: 'cat-2',
        image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Can be made dairy-free',
        allergens: 'Milk (optional)',
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Almond'], required: false }],
        order: 1
    },
    {
        id: 'item-8',
        name: 'Hot Chocolate',
        description: 'Premium Belgian chocolate melted into steamed milk, topped with marshmallows.',
        price: 135,
        categoryId: 'cat-2',
        image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Milk, Dairy',
        options: [],
        order: 2
    },
    {
        id: 'item-9',
        name: 'Turmeric Latte',
        description: 'Warming golden milk with turmeric, cinnamon, honey, and a hint of black pepper.',
        price: 150,
        categoryId: 'cat-2',
        image: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: '',
        allergens: 'Milk',
        options: [{ name: 'Sweetener', choices: ['Honey', 'Maple Syrup', 'None'], required: false }],
        order: 3
    },
    {
        id: 'item-10',
        name: 'Iced Americano',
        description: 'Chilled espresso over ice for a crisp, refreshing coffee experience.',
        price: 105,
        categoryId: 'cat-3',
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: '',
        options: [{ name: 'Size', choices: ['Regular', 'Large'], required: false }],
        order: 1
    },
    {
        id: 'item-11',
        name: 'Iced Latte',
        description: 'Cool espresso and cold milk over ice, perfectly balanced and refreshing.',
        price: 140,
        categoryId: 'cat-3',
        image: 'https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Milk',
        options: [{ name: 'Milk', choices: ['Whole', 'Oat', 'Soy'], required: false }],
        order: 2
    },
    {
        id: 'item-12',
        name: 'Cold Brew',
        description: 'Slow-steeped for 18 hours for a smooth, low-acidity coffee concentrate.',
        price: 155,
        categoryId: 'cat-3',
        image: 'https://images.unsplash.com/photo-1509042239860-f55023b724f1?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Available with oat milk',
        allergens: '',
        options: [],
        order: 3
    },
    {
        id: 'item-13',
        name: 'Butter Croissant',
        description: 'Flaky, golden, and perfectly buttery. Baked fresh every morning.',
        price: 110,
        categoryId: 'cat-4',
        image: 'https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Best served warm',
        allergens: 'Gluten, Dairy, Eggs',
        options: [],
        order: 1
    },
    {
        id: 'item-14',
        name: 'Almond Croissant',
        description: 'Buttery croissant filled with almond cream and topped with toasted almond flakes.',
        price: 140,
        categoryId: 'cat-4',
        image: 'https://images.unsplash.com/photo-1550614001-222b46d7098c?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Nuts, Eggs',
        options: [],
        order: 2
    },
    {
        id: 'item-15',
        name: 'Pain au Chocolat',
        description: 'Flaky croissant dough wrapped around rich dark chocolate batons.',
        price: 125,
        categoryId: 'cat-4',
        image: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Chocolate',
        options: [],
        order: 3
    },
    {
        id: 'item-16',
        name: 'Chocolate Layer Cake',
        description: 'Three layers of moist chocolate cake with ganache and dark chocolate shavings.',
        price: 280,
        categoryId: 'cat-5',
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop',
        tags: ['popular', 'featured'],
        available: true,
        featured: true,
        popular: true,
        note: 'Serves 2-3',
        allergens: 'Gluten, Dairy, Eggs',
        options: [],
        order: 1
    },
    {
        id: 'item-17',
        name: 'Caramel Cheesecake',
        description: 'Creamy New York cheesecake with a salted caramel drizzle and graham cracker crust.',
        price: 260,
        categoryId: 'cat-5',
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: '',
        allergens: 'Dairy, Gluten, Eggs',
        options: [],
        order: 2
    },
    {
        id: 'item-18',
        name: 'Tiramisu',
        description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream.',
        price: 240,
        categoryId: 'cat-5',
        image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Contains alcohol',
        allergens: 'Dairy, Gluten, Eggs, Alcohol',
        options: [],
        order: 3
    },
    {
        id: 'item-19',
        name: 'Custom Whole Cake',
        description: 'Design your own cake. Choose flavor, size, and decorations. 48-hour notice required.',
        price: 1200,
        categoryId: 'cat-6',
        image: 'https://images.unsplash.com/photo-1571115177098-24a42ab0f4c6?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: '48-hour advance order',
        allergens: 'Varies by flavor',
        options: [{ name: 'Flavor', choices: ['Chocolate', 'Vanilla', 'Red Velvet', 'Carrot'], required: true }, { name: 'Size', choices: ['6 inch', '8 inch', '10 inch'], required: true }],
        order: 1
    },
    {
        id: 'item-20',
        name: 'Full Breakfast',
        description: 'Scrambled eggs, grilled tomato, sausage, beans, toast, and hash browns.',
        price: 320,
        categoryId: 'cat-7',
        image: 'https://images.unsplash.com/photo-1533089862017-5614ec95e2d9?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Served with coffee or tea',
        allergens: 'Gluten, Dairy, Eggs',
        options: [],
        order: 1
    },
    {
        id: 'item-21',
        name: 'Avocado Toast',
        description: 'Sourdough bread topped with smashed avocado, chili flakes, sea salt, and microgreens.',
        price: 210,
        categoryId: 'cat-7',
        image: 'https://images.unsplash.com/photo-1541519227354-08fa2d2c9e12?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Add poached egg +45 ETB',
        allergens: 'Gluten',
        options: [{ name: 'Add', choices: ['Poached Egg', 'Feta Cheese', 'None'], required: false }],
        order: 2
    },
    {
        id: 'item-22',
        name: 'Club Sandwich',
        description: 'Triple-decker sandwich with roasted chicken, bacon, lettuce, tomato, and mayo.',
        price: 280,
        categoryId: 'cat-8',
        image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=400&fit=crop',
        tags: ['popular'],
        available: true,
        featured: false,
        popular: true,
        note: 'Served with fries',
        allergens: 'Gluten, Dairy',
        options: [],
        order: 1
    },
    {
        id: 'item-23',
        name: 'Pasta Carbonara',
        description: 'Spaghetti with creamy egg sauce, crispy pancetta, and parmesan.',
        price: 340,
        categoryId: 'cat-8',
        image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Gluten, Dairy, Eggs',
        options: [{ name: 'Add', choices: ['Extra Pancetta', 'Garlic Bread', 'None'], required: false }],
        order: 2
    },
    {
        id: 'item-24',
        name: 'Crème Brûlée',
        description: 'Rich vanilla custard with a caramelized sugar crust. Classic French dessert.',
        price: 190,
        categoryId: 'cat-9',
        image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&h=400&fit=crop',
        tags: [],
        available: true,
        featured: false,
        popular: false,
        note: '',
        allergens: 'Dairy, Eggs',
        options: [],
        order: 1
    },
    {
        id: 'item-25',
        name: 'Seasonal Fruit Plate',
        description: 'Fresh seasonal fruits beautifully arranged. Light and refreshing.',
        price: 170,
        categoryId: 'cat-9',
        image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400&h=400&fit=crop',
        tags: [],
        available: false,
        featured: false,
        popular: false,
        note: 'Subject to availability',
        allergens: '',
        options: [],
        order: 2
    },
    {
        id: 'item-26',
        name: 'Chef\'s Daily Special',
        description: 'Ask your server about today\'s special creation from our kitchen.',
        price: 350,
        categoryId: 'cat-10',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop',
        tags: ['featured'],
        available: true,
        featured: true,
        popular: false,
        note: 'Changes daily',
        allergens: 'Varies',
        options: [],
        order: 1
    }
];

function generateId(prefix) {
    return prefix + '-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
}
